version: "3.7"

services:
  postgresql:
    image: postgres:15.2-alpine
    restart: always
    container_name: postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    working_dir: /api
    container_name: php-fpm
    user: "${USER_UID:-1000}:${USER_GID:-1000}"
    volumes:
      - ./api:/api
    depends_on:
      - postgresql

  nginx:
    image: nginx:1.23.4-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/api
    ports:
      - "80:80"
    depends_on:
      - php-fpm
volumes:
  postgresql: